### ISSUE TITLE
Why do I get java.lang.ClassNotFoundException?

### ISSUE THREAD

**Issue by karnilaev** [codeborne/jvm2dts#1]
Hello.

I develop an application https://github.com/karnilaev/investing. I get following error during building:
```
> Task :inspectClassesForKotlinIC UP-TO-DATE
Packages detected: [auth, domain/portfolios]
// Failed to load: java.lang.ClassNotFoundException: domain/portfolios.Portfolio
```

As result file `types.ts` doesn't contain Portfolio interface

Class Portfolio exists in build directory:
```
./build/classes/kotlin/main
...
├── domain
│   └── portfolios
│       ├── Portfolio.class
│       ├── PortfolioController.class
│       ├── PortfolioRepository$mapper$1.class
│       └── PortfolioRepository.class

```

Could you please help me to find error in my config?

**Comment by angryziber** [comment]
Finding of nested packages fixed. Please also try the new option `-d` that filters Kotlin data classes
