### ISSUE TITLE
Doesn't work for poor Windows users

### ISSUE THREAD

**Issue by sgulyaev** [codeborne/jvm2dts#2]
Was trying to play with kotlin-jooby-svelte-template, but on Windows

"Files.walk(Paths.get(packageUrl.getPath()))" fails with exception:
Exception in thread "main" java.nio.file.InvalidPathException: Illegal char <:> at index 2: /K:/Projects/...

"Files.walk(Paths.get(packageUrl.toURI()))" works for me

**Comment by angryziber** [comment]
Thanks for the report, I've made your proposed change.
Does everything else work on Windows?

**Comment by sgulyaev** [comment]
Everything else is good. 
The only issue i stumbled is that one should clone "kotlin-jooby-svelte-template" with  git config core.autocrlf set to false.
Otherwise there are some problems with bash scripts.

**Comment by angryziber** [comment]
Ok, great. I tagged the fixed version as 1.6.4
